### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by fengzhongsu** [MingshanHe/Robotic_Arm_Algorithms#1]
ubuntu18.04 melodic
Robotic_Arm_Algorithms/universal_robot_control/cartesian_velocity_controller/include/cartesian_velocity_controller/kinematics_base.h:156:62: error: conversion from ‘urdf::LinkConstSharedPtr {aka std::shared_ptr<const urdf::Link>}’ to non-scalar type ‘boost::shared_ptr<const urdf::Link>’ requested
     boost::shared_ptr<const urdf::Link> link_ = model.getLink(tip_name);
                                                 ~~~~~~~~~~~~~^~~~~~~~~~

**Comment by MingshanHe** [comment]
It's recommended for using Ubuntu16.04 and this compile error is caused by the KDL library. I think it can be changed `boost::shared_ptr` to `std::shared_ptr`

**Comment by fengzhongsu** [comment]
您好，我已受到您的来信
