### ISSUE TITLE
Would it be possible to share your paper

### ISSUE THREAD

**Issue by HanwenCao** [MingshanHe/Robotic_Arm_Algorithms#2]
Hi! Thank you for your wonderful work. I was wondering if you have any publications/thesis regarding this project? If you have time, would you mind sharing your papers? That would be helpful for the community to understand your algorithms and follow your work. Thank you so much!

**Comment by MingshanHe** [comment]
Unfortunately, My paper has been rejected by this ICRA 2022. If you need the algorithm seriously, I think you can study the basic admittance control algorithm or search for some other papers about the admittance algorithm. I think it is a complete algorithm and there are so many resources to study.

**Comment by HanwenCao** [comment]
Sorry to hear the rejection. Thank you for your quick reply.
